// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.6.1
// source: interfases.proto

package Interfases

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LocationTracker_GetCoordinate_FullMethodName = "/Interfases.LocationTracker/getCoordinate"
)

// LocationTrackerClient is the client API for LocationTracker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocationTrackerClient interface {
	GetCoordinate(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Coordinate, error)
}

type locationTrackerClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationTrackerClient(cc grpc.ClientConnInterface) LocationTrackerClient {
	return &locationTrackerClient{cc}
}

func (c *locationTrackerClient) GetCoordinate(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Coordinate, error) {
	out := new(Coordinate)
	err := c.cc.Invoke(ctx, LocationTracker_GetCoordinate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationTrackerServer is the server API for LocationTracker service.
// All implementations must embed UnimplementedLocationTrackerServer
// for forward compatibility
type LocationTrackerServer interface {
	GetCoordinate(context.Context, *empty.Empty) (*Coordinate, error)
	mustEmbedUnimplementedLocationTrackerServer()
}

// UnimplementedLocationTrackerServer must be embedded to have forward compatible implementations.
type UnimplementedLocationTrackerServer struct {
}

func (UnimplementedLocationTrackerServer) GetCoordinate(context.Context, *empty.Empty) (*Coordinate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCoordinate not implemented")
}
func (UnimplementedLocationTrackerServer) mustEmbedUnimplementedLocationTrackerServer() {}

// UnsafeLocationTrackerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocationTrackerServer will
// result in compilation errors.
type UnsafeLocationTrackerServer interface {
	mustEmbedUnimplementedLocationTrackerServer()
}

func RegisterLocationTrackerServer(s grpc.ServiceRegistrar, srv LocationTrackerServer) {
	s.RegisterService(&LocationTracker_ServiceDesc, srv)
}

func _LocationTracker_GetCoordinate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationTrackerServer).GetCoordinate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationTracker_GetCoordinate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationTrackerServer).GetCoordinate(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// LocationTracker_ServiceDesc is the grpc.ServiceDesc for LocationTracker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocationTracker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Interfases.LocationTracker",
	HandlerType: (*LocationTrackerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getCoordinate",
			Handler:    _LocationTracker_GetCoordinate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interfases.proto",
}
