# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interfases.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10interfases.proto\x12\nInterfases\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"\"\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x32h\n\x0fLocationTracker\x12U\n\rgetCoordinate\x12\x16.google.protobuf.Empty\x1a\x16.Interfases.Coordinate\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\x0c/coordinatesB\x0eZ\x0c./Interfasesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interfases_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\014./Interfases'
  _LOCATIONTRACKER.methods_by_name['getCoordinate']._options = None
  _LOCATIONTRACKER.methods_by_name['getCoordinate']._serialized_options = b'\202\323\344\223\002\016\022\014/coordinates'
  _COORDINATE._serialized_start=91
  _COORDINATE._serialized_end=125
  _LOCATIONTRACKER._serialized_start=127
  _LOCATIONTRACKER._serialized_end=231
# @@protoc_insertion_point(module_scope)
